(in-package :clcomp)

(define-vop cons (res :register) ((arg1 :register :stack) (arg2 :register :stack))
  (inline-vop 'allocate res 2 $stack-top-operand$)
  (inst :mov *tmp-reg* arg1)
  (inst :mov (@ res) *tmp-reg*)
  (inst :mov *tmp-reg* arg2)
  (inst :mov (@ res nil nil *word-size*) *tmp-reg*)
  (inst :add res *list-tag*))

(define-vop car (res :register :stack) ((arg1 :register :stack))
  (inst :mov *tmp-reg* arg1)
  (inst :mov *tmp-reg* (@ *tmp-reg* nil nil (- *list-tag*)))
  (inst :mov res *tmp-reg*))

(define-vop inline-car (res :register :stack) ((arg1 :register :stack))
  (inst :mov res (@ arg1 nil nil (- *list-tag*))))

(define-vop rplaca (res :register :stack) ((arg1 :register :stack) (arg2 :register))
  (inst :mov *tmp-reg* arg1)
  (inst :mov (@ *tmp-reg* nil nil (- *list-tag*)) arg2)
  (inst :mov res *tmp-reg*))

(define-vop cdr (res :register :stack) ((arg1 :register :stack))
  (inst :mov *tmp-reg* arg1)
  (inst :mov *tmp-reg* (@ *tmp-reg* nil nil (- *word-size* *list-tag*)))
  (inst :mov res *tmp-reg*))

(define-vop inline-cdr (res :register) ((arg1 :register))
  (inst :mov res (@ arg1 nil nil (- *word-size* *list-tag*))))

(define-vop rplacd (res :register :stack) ((arg1 :register) (arg2 :register))
  (inst :mov *tmp-reg* arg1)
  (inst :mov (@ *tmp-reg* nil nil (- *word-size* *list-tag*)) arg2)
  (inst :mov *tmp-reg* res))

;; USE CMOV
(define-vop null (res :register) ((arg :register))
  (let ((eq-label (make-vop-label "eq"))
	(end-label (make-vop-label "end")))
    (inst :cmp arg *nil*)
    (inst :jump-fixup :je eq-label)
    (inst :mov res *nil*)
    (inst :jump-fixup :jmp end-label)
    (inst :label eq-label)
    (inst :mov res *t*)
    (inst :label end-label)))

;; USE CMOV
(define-vop listp (res :register) ((arg :register))
  (let ((list-label (make-vop-label "is-list"))
	(exit-label (make-vop-label "exit")))
    (inst :lea *tmp-reg* (@ arg nil nil (- *list-tag*)))
    (inst :test *tmp-reg* *mask*)
    (inst :jump-fixup :je list-label)
    (inst :mov res *nil*)
    (inst :jump-fixup :jmp exit-label)
    (inst :label list-label)
    (inst :mov res *t*)
    (inst :label exit-label)))
