(in-package :clcomp)

(define-vop %allocate-struct (res :register) ((slots :register)
					      (type :register :stack)
					      (layout :register :stack))
  (inst :mov res slots)
  (inst :shr res *fixnum-tag-size*)
  (inst :add res *struct-header-size*)
  (inline-vop 'allocate res res $stack-top-operand$)
  (inst :mov (@ res) (get-extended-tag 'struct))
  (inst :mov *tmp-reg* type)
  (inst :mov (@ res nil nil *word-size*)  *tmp-reg*)
  (inst :mov *tmp-reg* layout)
  (inst :mov (@ res nil nil (* 2 *word-size*)) *tmp-reg*)
  (inst :add res *pointer-tag*))

(define-vop %structp (res :register) ((arg :register))
  (let ((is-pointer-label (make-vop-label "is-pointer"))
	(is-struct-label (make-vop-label "is-struct"))
	(exit-label (make-vop-label "exit")))
    (inst :lea *tmp-reg* (@ arg nil nil (- *pointer-tag*)))
    (inst :test *tmp-reg* *mask*)
    (inst :jump-fixup :je is-pointer-label)
    (inst :mov res *nil*)
    (inst :jump-fixup :jmp exit-label)
    (inst :label is-pointer-label)
    (inst :cmp (@ :byte arg nil nil (- *pointer-tag*)) (get-extended-tag 'struct))
    (inst :jump-fixup :je is-struct-label)
    (inst :mov res *nil*)
    (inst :jump-fixup :jmp exit-label)
    (inst :label is-struct-label)
    (inst :mov res *t*)
    (inst :label exit-label)))

(define-vop %struct-type (res :register) ((struct :register))
  (inst :mov res (@ struct nil nil (- *word-size* *pointer-tag*))))

(define-vop %struct-layout (res :register) ((struct :register))
  (inst :mov res (@ struct nil nil (- (* 2 *word-size*) *pointer-tag*))))

(define-vop %get-struct-slot (res :register) ((struct :register)
					      (slot-index :register :stack))
  (inst :mov *tmp-reg* slot-index)
  (inst :shr *tmp-reg* *fixnum-tag-size*)
  (inst :mov res (@ struct *tmp-reg* *word-size* (- (* *struct-header-size* *word-size*)
						    *pointer-tag*))))


(define-vop %set-struct-slot (res :register :stack) ((struct :register)
						     (slot-index :register :stack)
						     (value :register))
  (inst :mov *tmp-reg* slot-index)
  (inst :shr *tmp-reg* *fixnum-tag-size*)
  (inst :mov (@ struct *tmp-reg* *word-size* (- (* *struct-header-size* *word-size*)
						*pointer-tag*)) value)
  (inst :mov res value))

